<a href="https://colab.research.google.com/github/kokohigh/DAO/blob/master/homework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import numpy as np

In [38]:
# Ko Kohei
# 21D50499

In [39]:
# FOR 1-NN
W1 = np.array([[0,0,1,0,0],
               [0,0,0,0,1],
               [1,0,0,1,0],
               [0,0,1,0,0],
               [0,1,0,0,0],])

D1 =np.array([[1,0,0,0,0],
               [0,1,0,0,0],
               [0,0,2,0,0],
               [0,0,0,1,0],
               [0,0,0,0,1],])
D_minus = np.array([[1**(-1/2),0,0,0,0],
               [0,1**(-1/2),0,0,0],
               [0,0,2**(-1/2),0,0],
               [0,0,0,1**(-1/2),0],
               [0,0,0,0,1**(-1/2)],])

Dstar = D_minus.dot(W1)
Df = Dstar.dot(D_minus)

result = np.linalg.eig(Df)
print(np.around(result[0], decimals=4))
print(np.around(result[1].T, decimals=4))

[-1.  0.  1.  1. -1.]
[[ 0.5     0.     -0.7071  0.5     0.    ]
 [-0.7071  0.     -0.      0.7071  0.    ]
 [ 0.5     0.      0.7071  0.5     0.    ]
 [ 0.     -0.7071  0.      0.     -0.7071]
 [ 0.     -0.7071  0.      0.      0.7071]]


In [40]:
u2 = np.array([0.5 ,    0.,      0.7071,  0.5,     0.],) # Which is the second eigenvector?
u1 = np.array([ 0. ,    -0.7071,  0. ,     0. ,    -0.7071],)
#u3 = np.array([-0.7071,  0.,     -0. ,     0.7071,  0.],)
#u1u2 = np.array([[0.5 ,    0.,      0.7071,  0.5,     0.],
                 #[ 0. ,    -0.7071,  0. ,     0. ,    -0.7071],])
print(np.around(D_minus.dot(u2),decimals=4))
print(np.around(D_minus.dot(u1),decimals=4))
#print(np.around(D_minus.dot(u3),decimals=4))
#print(np.around(D_minus.dot(u1u2.T).T,decimals=4))

[0.5 0.  0.5 0.5 0. ]
[ 0.     -0.7071  0.      0.     -0.7071]


In [41]:
# One of the above results should be the same constant, but I didn't get that. 
#So I don't know which result should be abandoned.

In [42]:
# FOR 2-NN
W1 = np.array([[0,1,1,1,0],
               [1,0,0,0,1],
               [1,0,0,1,0],
               [1,0,1,0,0],
               [0,1,0,0,0],])

D1 =np.array([[3,0,0,0,0],
               [0,2,0,0,0],
               [0,0,2,0,0],
               [0,0,0,2,0],
               [0,0,0,0,1],])
D_minus = np.array([[3**(-1/2),0,0,0,0],
               [0,2**(-1/2),0,0,0],
               [0,0,2**(-1/2),0,0],
               [0,0,0,2**(-1/2),0],
               [0,0,0,0,1**(-1/2)],])

Dstar = D_minus.dot(W1)
Df = Dstar.dot(D_minus)

result = np.linalg.eig(Df)
print(np.around(result[0], decimals=4, out=None))
print(np.around(result[1].T, decimals=4, out=None))

[ 1.      0.6541 -0.8566 -0.2975 -0.5   ]
[[-0.5477 -0.4472 -0.4472 -0.4472 -0.3162]
 [-0.1496  0.5531 -0.3964 -0.3964  0.5979]
 [-0.4497  0.6728  0.1353  0.1353 -0.5554]
 [-0.6895 -0.2035  0.353   0.353   0.4837]
 [-0.     -0.     -0.7071  0.7071  0.    ]]


In [43]:
u2 = np.array([-0.1496,  0.5531, -0.3964, -0.3964,  0.5979,],) #This is the second eigenvector
u1 = np.array([-0.5477, -0.4472, -0.4472, -0.4472, -0.3162,],)
print(np.around(D_minus.dot(u2),decimals = 4))
print(np.around(D_minus.dot(u1),decimals = 4)) 

[-0.0864  0.3911 -0.2803 -0.2803  0.5979]
[-0.3162 -0.3162 -0.3162 -0.3162 -0.3162]
